-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE FUNCTION updateMetaModified()
--   RETURNS TRIGGER
--   LANGUAGE PLPGSQL
--   AS
-- $$
-- BEGIN
-- 	UPDATE meta set modified = now() where id = OLD.meta_id;
-- 	return NEW;
-- END;
-- $$;
