-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE shared (
-- 	id serial PRIMARY KEY,
-- 	user_id varchar(50) not null,
-- 	sharing_id_list text default '[]'
-- );
