-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE TRIGGER updateMetaModifiedTrigger
-- BEFORE UPDATE
-- ON folder
-- FOR EACH ROW
-- EXECUTE PROCEDURE updateMetaModified();
