-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."file" add column "deleted_in_root_user_folder_id" integer
--  null;
